spring.application.name: QingDai-SP


qingdai:
  url: E:/QingDaiPhotos/
  fullSizeUrl: E:/QingDaiPhotos/Photos/FullSize/
  thumbnail1000KUrl: E:/QingDaiPhotos/Photos/Thumbnail-1000K/
  thumbnail100KUrl: E:/QingDaiPhotos/Photos/Thumbnail-100K/
  thumbnailSizeUrl: E:/QingDaiPhotos/Photos/Thumbnail/
  pendingUrl: E:/QingDaiPhotos/Photos/Pending/
  defaultAuthor: 皎月祝辞

server:
  servlet:
    context-path: /QingDai
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html # 文档页面路径
    operations-sorter: method # 接口排序方式
    tags-sorter: alpha      # 标签排序方式
  api-docs:
    path: /v3/api-docs      # OpenAPI描述文件路径
    groups:
      enabled: true         # 启用分组功能

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qingdai-photo?useUnicode=true&characterEncoding=utf-8&serverTimezoneGMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # 解决Spring Boot 3路径匹配问题
    hiddenmethod:
      filter:
        enabled: true
  aop:
    auto: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  data:
#    redis: localhost
#    host: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: com.qingdai.mapper/*.xml
  type-aliases-package: com.qingdai.pojo
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: hide
      logic-not-delete-value: 0
      logic-delete-value: 1
    enable-sql-runner: true




