qingdai:
  url:
    root: D:/QingDai Photos/
    fullSizeUrl: D:/QingDai Photos/Photos/FullSize/
    thumbnail1000KUrl: D:/QingDai Photos/Photos/Thumbnail-1000K/
    thumbnail100KUrl: D:/QingDai Photos/Photos/Thumbnail-100K/
    thumbnailSizeUrl: D:/QingDai Photos/Photos/Thumbnail/
    pendingUrl: D:/QingDai Photos/Photos/Pending/
    introduceUrl: D:/QingDai Photos/Photos/Introduce/
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qingdai-photo?useUnicode=true&characterEncoding=utf-8&serverTimezoneGMT%2B8
    username: root
    password: 123456
  data:
    redis:
      host: 129.226.192.212
      port: 6379

rocketmq:
  name-server: localhost:9876

