spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qingdai-photo?useUnicode=true&characterEncoding=utf-8&serverTimezoneGMT%2B8
    username: root
    password: 123456

qingdai:
  url: D:/QingDai Photos/
  fullSizeUrl: D:/Qing DaiPhotos/Photos/FullSize/
  thumbnail1000KUrl: D:/QingDai Photos/Photos/Thumbnail-1000K/
  thumbnail100KUrl: D:/QingDai Photos/Photos/Thumbnail-100K/
  thumbnailSizeUrl: D:/QingDai Photos/Photos/Thumbnail/
  pendingUrl: D:/QingDai Photos/Photos/Pending/